package neda

type Instruction struct {
	OpecodeType    OpecodeType
	AddressingType AddressingType
	Bytes          int
	Cycle          int
}

var InstructionMap = map[int]Instruction{
	0x00: {
		OpecodeType:    OpecodeBRK,
		AddressingType: AddressingTypeImplied,
		Bytes:          1,
		Cycle:          7,
	},
	0x01: {
		OpecodeType:    OpecodeORA,
		AddressingType: AddressingTypeIndirectX,
		Bytes:          2,
		Cycle:          6,
	},
	0x05: {
		OpecodeType:    OpecodeORA,
		AddressingType: AddressingTypeZeroPage,
		Bytes:          2,
		Cycle:          3,
	},
	0x06: {
		OpecodeType:    OpecodeASL,
		AddressingType: AddressingTypeZeroPage,
		Bytes:          2,
		Cycle:          5,
	},
	0x08: {
		OpecodeType:    OpecodePHP,
		AddressingType: AddressingTypeImplied,
		Bytes:          1,
		Cycle:          3,
	},
	0x09: {
		OpecodeType:    OpecodeORA,
		AddressingType: AddressingTypeImmediate,
		Bytes:          2,
		Cycle:          2,
	},
	0x0A: {
		OpecodeType:    OpecodeASL,
		AddressingType: AddressingTypeAccumulator,
		Bytes:          1,
		Cycle:          2,
	},
	0x0D: {
		OpecodeType:    OpecodeORA,
		AddressingType: AddressingTypeAbsolute,
		Bytes:          3,
		Cycle:          4,
	},
	0x0E: {
		OpecodeType:    OpecodeASL,
		AddressingType: AddressingTypeAbsolute,
		Bytes:          3,
		Cycle:          6,
	},
	0x10: {
		OpecodeType:    OpecodeBPL,
		AddressingType: AddressingTypeRelative,
		Bytes:          2,
		Cycle:          2,
	},
	0x11: {
		OpecodeType:    OpecodeORA,
		AddressingType: AddressingTypeIndirectY,
		Bytes:          2,
		Cycle:          5,
	},
	0x15: {
		OpecodeType:    OpecodeORA,
		AddressingType: AddressingTypeZeroPageX,
		Bytes:          2,
		Cycle:          4,
	},
	0x16: {
		OpecodeType:    OpecodeASL,
		AddressingType: AddressingTypeZeroPageX,
		Bytes:          2,
		Cycle:          6,
	},
	0x18: {
		OpecodeType:    OpecodeCLC,
		AddressingType: AddressingTypeImplied,
		Bytes:          1,
		Cycle:          2,
	},
	0x19: {
		OpecodeType:    OpecodeORA,
		AddressingType: AddressingTypeAbsoluteY,
		Bytes:          3,
		Cycle:          4,
	},
	0x1D: {
		OpecodeType:    OpecodeORA,
		AddressingType: AddressingTypeAbsoluteX,
		Bytes:          3,
		Cycle:          4,
	},
	0x1E: {
		OpecodeType:    OpecodeASL,
		AddressingType: AddressingTypeAbsoluteX,
		Bytes:          3,
		Cycle:          7,
	},
	0x20: {
		OpecodeType:    OpecodeJSR,
		AddressingType: AddressingTypeAbsolute,
		Bytes:          3,
		Cycle:          6,
	},
	0x21: {
		OpecodeType:    OpecodeAND,
		AddressingType: AddressingTypeIndirectX,
		Bytes:          2,
		Cycle:          6,
	},
	0x24: {
		OpecodeType:    OpecodeBIT,
		AddressingType: AddressingTypeZeroPage,
		Bytes:          2,
		Cycle:          3,
	},
	0x25: {
		OpecodeType:    OpecodeAND,
		AddressingType: AddressingTypeZeroPage,
		Bytes:          2,
		Cycle:          3,
	},
	0x26: {
		OpecodeType:    OpecodeROL,
		AddressingType: AddressingTypeZeroPage,
		Bytes:          2,
		Cycle:          5,
	},
	0x28: {
		OpecodeType:    OpecodePLP,
		AddressingType: AddressingTypeImplied,
		Bytes:          1,
		Cycle:          4,
	},
	0x29: {
		OpecodeType:    OpecodeAND,
		AddressingType: AddressingTypeImmediate,
		Bytes:          2,
		Cycle:          2,
	},
	0x2A: {
		OpecodeType:    OpecodeROL,
		AddressingType: AddressingTypeAccumulator,
		Bytes:          1,
		Cycle:          2,
	},
	0x2C: {
		OpecodeType:    OpecodeBIT,
		AddressingType: AddressingTypeAbsolute,
		Bytes:          3,
		Cycle:          4,
	},
	0x2D: {
		OpecodeType:    OpecodeAND,
		AddressingType: AddressingTypeAbsolute,
		Bytes:          3,
		Cycle:          4,
	},
	0x2E: {
		OpecodeType:    OpecodeROL,
		AddressingType: AddressingTypeAbsolute,
		Bytes:          3,
		Cycle:          6,
	},
	0x30: {
		OpecodeType:    OpecodeBMI,
		AddressingType: AddressingTypeRelative,
		Bytes:          2,
		Cycle:          2,
	},
	0x31: {
		OpecodeType:    OpecodeAND,
		AddressingType: AddressingTypeIndirectY,
		Bytes:          2,
		Cycle:          5,
	},
	0x35: {
		OpecodeType:    OpecodeAND,
		AddressingType: AddressingTypeZeroPageX,
		Bytes:          2,
		Cycle:          4,
	},
	0x36: {
		OpecodeType:    OpecodeROL,
		AddressingType: AddressingTypeZeroPageX,
		Bytes:          2,
		Cycle:          6,
	},
	0x38: {
		OpecodeType:    OpecodeSEC,
		AddressingType: AddressingTypeImplied,
		Bytes:          1,
		Cycle:          2,
	},
	0x39: {
		OpecodeType:    OpecodeAND,
		AddressingType: AddressingTypeAbsoluteY,
		Bytes:          3,
		Cycle:          4,
	},
	0x3D: {
		OpecodeType:    OpecodeAND,
		AddressingType: AddressingTypeAbsoluteX,
		Bytes:          3,
		Cycle:          4,
	},
	0x3E: {
		OpecodeType:    OpecodeROL,
		AddressingType: AddressingTypeAbsoluteX,
		Bytes:          3,
		Cycle:          7,
	},
	0x40: {
		OpecodeType:    OpecodeRTI,
		AddressingType: AddressingTypeImplied,
		Bytes:          1,
		Cycle:          6,
	},
	0x41: {
		OpecodeType:    OpecodeEOR,
		AddressingType: AddressingTypeIndirectX,
		Bytes:          2,
		Cycle:          6,
	},
	0x45: {
		OpecodeType:    OpecodeEOR,
		AddressingType: AddressingTypeZeroPage,
		Bytes:          2,
		Cycle:          3,
	},
	0x46: {
		OpecodeType:    OpecodeLSR,
		AddressingType: AddressingTypeZeroPage,
		Bytes:          2,
		Cycle:          5,
	},
	0x48: {
		OpecodeType:    OpecodePHA,
		AddressingType: AddressingTypeImplied,
		Bytes:          1,
		Cycle:          3,
	},
	0x49: {
		OpecodeType:    OpecodeEOR,
		AddressingType: AddressingTypeImmediate,
		Bytes:          2,
		Cycle:          3,
	},
	0x4A: {
		OpecodeType:    OpecodeLSR,
		AddressingType: AddressingTypeAccumulator,
		Bytes:          1,
		Cycle:          2,
	},
	0x4C: {
		OpecodeType:    OpecodeJMP,
		AddressingType: AddressingTypeAbsolute,
		Bytes:          3,
		Cycle:          3,
	},
	0x4D: {
		OpecodeType:    OpecodeEOR,
		AddressingType: AddressingTypeAbsolute,
		Bytes:          3,
		Cycle:          4,
	},
	0x4E: {
		OpecodeType:    OpecodeLSR,
		AddressingType: AddressingTypeAbsolute,
		Bytes:          3,
		Cycle:          6,
	},
	0x50: {
		OpecodeType:    OpecodeBVC,
		AddressingType: AddressingTypeRelative,
		Bytes:          2,
		Cycle:          2,
	},
	0x51: {
		OpecodeType:    OpecodeEOR,
		AddressingType: AddressingTypeIndirectY,
		Bytes:          2,
		Cycle:          5,
	},
	0x55: {
		OpecodeType:    OpecodeEOR,
		AddressingType: AddressingTypeZeroPageX,
		Bytes:          2,
		Cycle:          4,
	},
	0x56: {
		OpecodeType:    OpecodeLSR,
		AddressingType: AddressingTypeZeroPageX,
		Bytes:          2,
		Cycle:          6,
	},
	0x58: {
		OpecodeType:    OpecodeCLI,
		AddressingType: AddressingTypeImplied,
		Bytes:          1,
		Cycle:          2,
	},
	0x59: {
		OpecodeType:    OpecodeEOR,
		AddressingType: AddressingTypeAbsoluteY,
		Bytes:          3,
		Cycle:          4,
	},
	0x5D: {
		OpecodeType:    OpecodeEOR,
		AddressingType: AddressingTypeAbsoluteX,
		Bytes:          3,
		Cycle:          4,
	},
	0x5E: {
		OpecodeType:    OpecodeLSR,
		AddressingType: AddressingTypeAbsoluteX,
		Bytes:          3,
		Cycle:          7,
	},
	0x60: {
		OpecodeType:    OpecodeRTS,
		AddressingType: AddressingTypeImplied,
		Bytes:          1,
		Cycle:          6,
	},
	0x61: {
		OpecodeType:    OpecodeADC,
		AddressingType: AddressingTypeIndirectX,
		Bytes:          2,
		Cycle:          6,
	},
	0x65: {
		OpecodeType:    OpecodeADC,
		AddressingType: AddressingTypeZeroPage,
		Bytes:          2,
		Cycle:          3,
	},
	0x66: {
		OpecodeType:    OpecodeROR,
		AddressingType: AddressingTypeZeroPage,
		Bytes:          2,
		Cycle:          5,
	},
	0x68: {
		OpecodeType:    OpecodePLA,
		AddressingType: AddressingTypeImplied,
		Bytes:          1,
		Cycle:          4,
	},
	0x69: {
		OpecodeType:    OpecodeADC,
		AddressingType: AddressingTypeImmediate,
		Bytes:          2,
		Cycle:          2,
	},
	0x6A: {
		OpecodeType:    OpecodeROR,
		AddressingType: AddressingTypeAccumulator,
		Bytes:          1,
		Cycle:          2,
	},
	0x6C: {
		OpecodeType:    OpecodeJMP,
		AddressingType: AddressingTypeIndirect,
		Bytes:          3,
		Cycle:          5,
	},
	0x6D: {
		OpecodeType:    OpecodeADC,
		AddressingType: AddressingTypeAbsolute,
		Bytes:          3,
		Cycle:          4,
	},
	0x6E: {
		OpecodeType:    OpecodeROR,
		AddressingType: AddressingTypeAbsolute,
		Bytes:          3,
		Cycle:          6,
	},
	0x70: {
		OpecodeType:    OpecodeBVS,
		AddressingType: AddressingTypeRelative,
		Bytes:          2,
		Cycle:          2,
	},
	0x71: {
		OpecodeType:    OpecodeADC,
		AddressingType: AddressingTypeAbsoluteY,
		Bytes:          2,
		Cycle:          5,
	},
	0x75: {
		OpecodeType:    OpecodeADC,
		AddressingType: AddressingTypeZeroPageX,
		Bytes:          2,
		Cycle:          4,
	},
	0x76: {
		OpecodeType:    OpecodeROR,
		AddressingType: AddressingTypeZeroPageX,
		Bytes:          2,
		Cycle:          6,
	},
	0x78: {
		OpecodeType:    OpecodeSEI,
		AddressingType: AddressingTypeImplied,
		Bytes:          1,
		Cycle:          2,
	},
	0x79: {
		OpecodeType:    OpecodeADC,
		AddressingType: AddressingTypeAbsoluteY,
		Bytes:          3,
		Cycle:          4,
	},
	0x7D: {
		OpecodeType:    OpecodeADC,
		AddressingType: AddressingTypeAbsoluteX,
		Bytes:          3,
		Cycle:          4,
	},
	0x7E: {
		OpecodeType:    OpecodeROR,
		AddressingType: AddressingTypeAbsoluteX,
		Bytes:          3,
		Cycle:          7,
	},
	0x81: {
		OpecodeType:    OpecodeSTA,
		AddressingType: AddressingTypeIndirectX,
		Bytes:          2,
		Cycle:          6,
	},
	0x84: {
		OpecodeType:    OpecodeSTY,
		AddressingType: AddressingTypeZeroPage,
		Bytes:          2,
		Cycle:          3,
	},
	0x85: {
		OpecodeType:    OpecodeSTA,
		AddressingType: AddressingTypeZeroPage,
		Bytes:          2,
		Cycle:          3,
	},
	0x86: {
		OpecodeType:    OpecodeSTX,
		AddressingType: AddressingTypeZeroPage,
		Bytes:          2,
		Cycle:          3,
	},
	0x88: {
		OpecodeType:    OpecodeDEY,
		AddressingType: AddressingTypeImplied,
		Bytes:          1,
		Cycle:          2,
	},
	0x8A: {
		OpecodeType:    OpecodeTXA,
		AddressingType: AddressingTypeImplied,
		Bytes:          1,
		Cycle:          2,
	},
	0x8C: {
		OpecodeType:    OpecodeSTY,
		AddressingType: AddressingTypeAbsolute,
		Bytes:          3,
		Cycle:          4,
	},
	0x8D: {
		OpecodeType:    OpecodeSTA,
		AddressingType: AddressingTypeAbsolute,
		Bytes:          3,
		Cycle:          4,
	},
	0x8E: {
		OpecodeType:    OpecodeSTX,
		AddressingType: AddressingTypeAbsolute,
		Bytes:          3,
		Cycle:          4,
	},
	0x90: {
		OpecodeType:    OpecodeBCC,
		AddressingType: AddressingTypeRelative,
		Bytes:          2,
		Cycle:          2,
	},
	0x91: {
		OpecodeType:    OpecodeSTA,
		AddressingType: AddressingTypeIndirectY,
		Bytes:          2,
		Cycle:          6,
	},
	0x94: {
		OpecodeType:    OpecodeSTY,
		AddressingType: AddressingTypeZeroPageX,
		Bytes:          2,
		Cycle:          4,
	},
	0x95: {
		OpecodeType:    OpecodeSTA,
		AddressingType: AddressingTypeZeroPageX,
		Bytes:          2,
		Cycle:          4,
	},
	0x96: {
		OpecodeType:    OpecodeSTX,
		AddressingType: AddressingTypeZeroPageY,
		Bytes:          2,
		Cycle:          4,
	},
	0x98: {
		OpecodeType:    OpecodeTYA,
		AddressingType: AddressingTypeImplied,
		Bytes:          1,
		Cycle:          2,
	},
	0x99: {
		OpecodeType:    OpecodeSTA,
		AddressingType: AddressingTypeAbsoluteY,
		Bytes:          3,
		Cycle:          5,
	},
	0x9A: {
		OpecodeType:    OpecodeTXS,
		AddressingType: AddressingTypeImplied,
		Bytes:          1,
		Cycle:          2,
	},
	0x9D: {
		OpecodeType:    OpecodeSTA,
		AddressingType: AddressingTypeAbsoluteX,
		Bytes:          3,
		Cycle:          5,
	},
	0xA0: {
		OpecodeType:    OpecodeLDY,
		AddressingType: AddressingTypeImmediate,
		Bytes:          2,
		Cycle:          2,
	},
	0xA1: {
		OpecodeType:    OpecodeLDA,
		AddressingType: AddressingTypeIndirectX,
		Bytes:          2,
		Cycle:          6,
	},
	0xA2: {
		OpecodeType:    OpecodeLDX,
		AddressingType: AddressingTypeImmediate,
		Bytes:          2,
		Cycle:          2,
	},
	0xA4: {
		OpecodeType:    OpecodeLDY,
		AddressingType: AddressingTypeZeroPage,
		Bytes:          2,
		Cycle:          3,
	},
	0xA5: {
		OpecodeType:    OpecodeLDA,
		AddressingType: AddressingTypeZeroPage,
		Bytes:          2,
		Cycle:          3,
	},
	0xA6: {
		OpecodeType:    OpecodeLDX,
		AddressingType: AddressingTypeZeroPage,
		Bytes:          2,
		Cycle:          3,
	},
	0xA8: {
		OpecodeType:    OpecodeTAY,
		AddressingType: AddressingTypeImplied,
		Bytes:          1,
		Cycle:          2,
	},
	0xA9: {
		OpecodeType:    OpecodeLDA,
		AddressingType: AddressingTypeImmediate,
		Bytes:          2,
		Cycle:          2,
	},
	0xAA: {
		OpecodeType:    OpecodeTAX,
		AddressingType: AddressingTypeImplied,
		Bytes:          1,
		Cycle:          2,
	},
	0xAC: {
		OpecodeType:    OpecodeLDY,
		AddressingType: AddressingTypeAbsolute,
		Bytes:          3,
		Cycle:          4,
	},
	0xAD: {
		OpecodeType:    OpecodeLDA,
		AddressingType: AddressingTypeAbsolute,
		Bytes:          3,
		Cycle:          4,
	},
	0xAE: {
		OpecodeType:    OpecodeLDX,
		AddressingType: AddressingTypeAbsolute,
		Bytes:          3,
		Cycle:          4,
	},
	0xB0: {
		OpecodeType:    OpecodeBCS,
		AddressingType: AddressingTypeRelative,
		Bytes:          2,
		Cycle:          2,
	},
	0xB1: {
		OpecodeType:    OpecodeLDA,
		AddressingType: AddressingTypeIndirectY,
		Bytes:          2,
		Cycle:          5,
	},
	0xB4: {
		OpecodeType:    OpecodeLDY,
		AddressingType: AddressingTypeZeroPageX,
		Bytes:          2,
		Cycle:          4,
	},
	0xB5: {
		OpecodeType:    OpecodeLDA,
		AddressingType: AddressingTypeZeroPageX,
		Bytes:          2,
		Cycle:          4,
	},
	0xB6: {
		OpecodeType:    OpecodeLDX,
		AddressingType: AddressingTypeZeroPageY,
		Bytes:          2,
		Cycle:          4,
	},
	0xB8: {
		OpecodeType:    OpecodeCLV,
		AddressingType: AddressingTypeImplied,
		Bytes:          1,
		Cycle:          2,
	},
	0xB9: {
		OpecodeType:    OpecodeLDA,
		AddressingType: AddressingTypeAbsoluteY,
		Bytes:          3,
		Cycle:          4,
	},
	0xBA: {
		OpecodeType:    OpecodeTSX,
		AddressingType: AddressingTypeImplied,
		Bytes:          1,
		Cycle:          2,
	},
	0xBC: {
		OpecodeType:    OpecodeLDY,
		AddressingType: AddressingTypeAbsolute,
		Bytes:          3,
		Cycle:          4,
	},
	0xBD: {
		OpecodeType:    OpecodeLDA,
		AddressingType: AddressingTypeAbsoluteX,
		Bytes:          3,
		Cycle:          4,
	},
	0xBE: {
		OpecodeType:    OpecodeLDX,
		AddressingType: AddressingTypeAbsoluteY,
		Bytes:          3,
		Cycle:          4,
	},
	0xC0: {
		OpecodeType:    OpecodeCPY,
		AddressingType: AddressingTypeImmediate,
		Bytes:          2,
		Cycle:          2,
	},
	0xC1: {
		OpecodeType:    OpecodeCMP,
		AddressingType: AddressingTypeIndirectX,
		Bytes:          2,
		Cycle:          6,
	},
	0xC4: {
		OpecodeType:    OpecodeCPY,
		AddressingType: AddressingTypeZeroPage,
		Bytes:          2,
		Cycle:          3,
	},
	0xC5: {
		OpecodeType:    OpecodeCMP,
		AddressingType: AddressingTypeZeroPage,
		Bytes:          2,
		Cycle:          3,
	},
	0xC6: {
		OpecodeType:    OpecodeDEC,
		AddressingType: AddressingTypeZeroPage,
		Bytes:          2,
		Cycle:          5,
	},
	0xC8: {
		OpecodeType:    OpecodeINY,
		AddressingType: AddressingTypeImplied,
		Bytes:          1,
		Cycle:          2,
	},
	0xC9: {
		OpecodeType:    OpecodeCMP,
		AddressingType: AddressingTypeImmediate,
		Bytes:          2,
		Cycle:          2,
	},
	0xCA: {
		OpecodeType:    OpecodeDEX,
		AddressingType: AddressingTypeImplied,
		Bytes:          1,
		Cycle:          2,
	},
	0xCC: {
		OpecodeType:    OpecodeCPY,
		AddressingType: AddressingTypeAbsolute,
		Bytes:          3,
		Cycle:          4,
	},
	0xCD: {
		OpecodeType:    OpecodeCMP,
		AddressingType: AddressingTypeAbsolute,
		Bytes:          3,
		Cycle:          4,
	},
	0xCE: {
		OpecodeType:    OpecodeDEC,
		AddressingType: AddressingTypeAbsolute,
		Bytes:          3,
		Cycle:          6,
	},
	0xD0: {
		OpecodeType:    OpecodeBNE,
		AddressingType: AddressingTypeRelative,
		Bytes:          2,
		Cycle:          2,
	},
	0xD1: {
		OpecodeType:    OpecodeCMP,
		AddressingType: AddressingTypeIndirectY,
		Bytes:          2,
		Cycle:          5,
	},
	0xD5: {
		OpecodeType:    OpecodeCMP,
		AddressingType: AddressingTypeZeroPageX,
		Bytes:          2,
		Cycle:          4,
	},
	0xD6: {
		OpecodeType:    OpecodeDEC,
		AddressingType: AddressingTypeZeroPageX,
		Bytes:          2,
		Cycle:          6,
	},
	0xD8: {
		OpecodeType:    OpecodeCLD,
		AddressingType: AddressingTypeImplied,
		Bytes:          1,
		Cycle:          2,
	},
	0xD9: {
		OpecodeType:    OpecodeCMP,
		AddressingType: AddressingTypeAbsoluteY,
		Bytes:          3,
		Cycle:          4,
	},
	0xDD: {
		OpecodeType:    OpecodeCMP,
		AddressingType: AddressingTypeAbsoluteX,
		Bytes:          3,
		Cycle:          4,
	},
	0xDE: {
		OpecodeType:    OpecodeDEC,
		AddressingType: AddressingTypeAbsoluteX,
		Bytes:          3,
		Cycle:          7,
	},
	0xE0: {
		OpecodeType:    OpecodeCPX,
		AddressingType: AddressingTypeImmediate,
		Bytes:          2,
		Cycle:          2,
	},
	0xE1: {
		OpecodeType:    OpecodeSBC,
		AddressingType: AddressingTypeIndirectX,
		Bytes:          2,
		Cycle:          6,
	},
	0xE4: {
		OpecodeType:    OpecodeCPX,
		AddressingType: AddressingTypeZeroPage,
		Bytes:          2,
		Cycle:          3,
	},
	0xE5: {
		OpecodeType:    OpecodeSBC,
		AddressingType: AddressingTypeZeroPage,
		Bytes:          2,
		Cycle:          3,
	},
	0xE6: {
		OpecodeType:    OpecodeINC,
		AddressingType: AddressingTypeZeroPage,
		Bytes:          2,
		Cycle:          5,
	},
	0xE8: {
		OpecodeType:    OpecodeINX,
		AddressingType: AddressingTypeImplied,
		Bytes:          1,
		Cycle:          2,
	},
	0xE9: {
		OpecodeType:    OpecodeSBC,
		AddressingType: AddressingTypeImmediate,
		Bytes:          2,
		Cycle:          2,
	},
	0xEA: {
		OpecodeType:    OpecodeNOP,
		AddressingType: AddressingTypeImplied,
		Bytes:          1,
		Cycle:          2,
	},
	0xEC: {
		OpecodeType:    OpecodeCPX,
		AddressingType: AddressingTypeAbsolute,
		Bytes:          3,
		Cycle:          4,
	},
	0xED: {
		OpecodeType:    OpecodeSBC,
		AddressingType: AddressingTypeAbsolute,
		Bytes:          3,
		Cycle:          4,
	},
	0xEE: {
		OpecodeType:    OpecodeINC,
		AddressingType: AddressingTypeAbsolute,
		Bytes:          3,
		Cycle:          6,
	},
	0xF0: {
		OpecodeType:    OpecodeBEQ,
		AddressingType: AddressingTypeRelative,
		Bytes:          2,
		Cycle:          2,
	},
	0xF1: {
		OpecodeType:    OpecodeSBC,
		AddressingType: AddressingTypeIndirectY,
		Bytes:          2,
		Cycle:          5,
	},
	0xF5: {
		OpecodeType:    OpecodeSBC,
		AddressingType: AddressingTypeZeroPageX,
		Bytes:          2,
		Cycle:          4,
	},
	0xF6: {
		OpecodeType:    OpecodeINC,
		AddressingType: AddressingTypeZeroPageX,
		Bytes:          2,
		Cycle:          6,
	},
	0xF8: {
		OpecodeType:    OpecodeSED,
		AddressingType: AddressingTypeImplied,
		Bytes:          1,
		Cycle:          2,
	},
	0xF9: {
		OpecodeType:    OpecodeSBC,
		AddressingType: AddressingTypeAbsoluteY,
		Bytes:          3,
		Cycle:          4,
	},
	0xFD: {
		OpecodeType:    OpecodeSBC,
		AddressingType: AddressingTypeAbsoluteX,
		Bytes:          3,
		Cycle:          4,
	},
	0xFE: {
		OpecodeType:    OpecodeINC,
		AddressingType: AddressingTypeAbsoluteX,
		Bytes:          3,
		Cycle:          7,
	},
}
